defaultSemverRangePrefix: ""

logFilters:
  - code: YN0006
    level: discard

npmAuthToken: "${NPM_TOKEN-}"

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.0.2.cjs
