name: Main

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build
        run: yarn build:ci

      - name: Lint
        run: yarn lint

      - name: Version
        id: version
        if: github.event_name == 'push'
        uses: TriPSs/conventional-changelog-action@v3

      - name: Publish
        if: ${{ steps.version.outputs.skipped == 'false' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn npm publish

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.version.outputs.skipped == 'false' }}
        with:
          body: ${{ steps.version.outputs.clean_changelog }}
          tag_name: ${{ steps.version.outputs.tag }}
